apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vertical-text-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU・メモリ設定
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        # タイムアウト設定
        run.googleapis.com/timeout: "300"
        # 同時実行数
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 10
      containers:
      - image: gcr.io/manganamemaker/vertical-text-api
        ports:
        - containerPort: 8080
        env:
        - name: API_TOKEN
          value: "manganamemaker-secret-token"
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        # ヘルスチェック
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
