services:
  vertical-text-generator:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"  # 8000番ポートで公開
    environment:
      - PYTHONUNBUFFERED=1
      - API_TOKEN=${API_TOKEN}  # .envファイルから自動的に読み込まれます
    env_file:
      - .env  # .envファイルを明示的に指定
    volumes:
      # フォントディレクトリをマウント
      - ./fonts:/app/fonts:ro  # 読み取り専用でマウント
      # ログファイルをホストにマウント
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Chrome/Playwrightの初期化に時間がかかるため
    # Chrome実行用の追加設定
    security_opt:
      - seccomp:unconfined
    shm_size: 4g         # 2gb → 4gb に拡張（必要なら）
    mem_limit: 8g         # コンテナのハード上限
    mem_reservation: 6g   # これ以下で動くのが理想
    memswap_limit: 8g     # スワップを使わせない（mem_limit と同値）
    mem_swappiness: 10    # 低スワップ化
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # pids_limit: 512     # 必要ならPIDの上限も設定
    # command を上書きしてUvicornの制御（下のセクション参照）
    command: >
      sh -c "uvicorn main:app
      --host 0.0.0.0 --port 8000
      --workers ${UVICORN_WORKERS:-1}
      --limit-concurrency ${UVICORN_LIMIT_CONCURRENCY:-64}
      --limit-max-requests ${UVICORN_LIMIT_MAX_REQUESTS:-500}
      --timeout-keep-alive ${UVICORN_TIMEOUT_KEEP_ALIVE:-15}"
